### ISSUE TITLE
I can't find google-service.json

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [vshkl/PXLSRT#12]
hi i can't find google-services.json file inside the project

**Comment by vshkl** [comment]
Hi! You can't find it 'cuz it shouldn't be there. It's in [gitignore](https://github.com/vshkl/PXLSRT/blob/c48399e974b1ee844823b9ee6119301c22b520d0/.gitignore#L51)
You should use your own `google-services.json` file. You can refer [here](https://support.google.com/firebase/answer/7015592?hl=en) to find you how to get it.
